### ISSUE TITLE
Feature request: Bright and dim term colors

### ISSUE THREAD

**Issue by mreinhardt** [AlessandroYorba/Arcadia#2]
It would be nice to have both bright and dim term colors in the [https://github.com/AlessandroYorba/Arcadia/blob/master/terminal_colors/arcadia.Xresources](.Xresources) and .itermcolors files. I ended up making my own by reducing the brightness to 2/3 but an officially sanctioned scheme according to whatever color theory insights you have would be nice. Here's what I ended up with for purposes of example:

```
! special
*.foreground:   #e4e4e4
*.background:   #303030
*.cursorColor:  #e4e4e4

! black
*.color0:       #101010
*.color8:       #303030

! red
*.color1:       #8e053e
*.color9:       #af1c5f

! green
*.color2:       #216666
*.color10:      #008787

! yellow
*.color3:       #be8e21
*.color11:      #dfaf00

! blue
*.color4:       #3e668e
*.color12:      #5f87af

! magenta
*.color5:       #663e66
*.color13:      #875f87

! cyan
*.color6:       #21668e
*.color14:      #0087af

! white
*.color7:       #c3c3c3
*.color15:      #e4e4e4
```

**Comment by AlessandroYorba** [comment]
I added your colors to iTerm to test them out. I think it looks awesome. I've always wanted to do something like this where the terminal had Normal and Bright color variation. I always hesitated because I assumed that users would want the terminal colors [0-7] to match the 256 colors found in the vim scheme. Do you want to send a PR?
Also, there might be 1 or 2 darker colors in the scheme that we might use but I don't know if they would look any good. I send them over to you and you can tell me if we should consider them. Thanks dude!

**Comment by mreinhardt** [comment]
Sure thing, I'll make a PR. I have a question though, I notice you mostly use standard 256-xterm values to construct your colors (00, 5f, 87, af, etc)... do you want me to try to get the darker colors to use those hex values too so they'd directly translate to standard cterm colors, or does it not matter?

**Comment by AlessandroYorba** [comment]
Hmmm, good question. I really don't know. Your call

**Comment by AlessandroYorba** [comment]
Done!
